version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server
    user: "0:0"
    networks:
      - mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TempSA_Password123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql/data
      - mssql_log:/var/opt/mssql/log
      - mssql_secrets:/var/opt/mssql/secrets
      - ./init-db.sql:/docker-entrypoint-initdb.d
    restart: unless-stopped
    command: >
      bash -c "
      /opt/mssql/bin/sqlservr &
      chmod +x /docker-entrypoint-initdb.d/run-initialization.sh &&
      /docker-entrypoint-initdb.d/run-initialization.sh &
      wait
      "
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P TempSA_Password123! -C -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s


volumes:
  mssql_data:
  mssql_log:
  mssql_secrets:


networks:
  mssql:
    driver: bridge
