version: 2

sources:
  - name: input_db
    database: "{{ env_var('DBT_INPUT_DB_NAME') }}"
    schema: cso
    tables:
      - name: DimChannel
      - name: DimCurrency
      - name: DimCustomer
      - name: DimDate
      - name: DimGeography
      - name: DimProduct
      - name: DimProductCategory
      - name: DimProductSubcategory
      - name: DimPromotion
      - name: DimStore
      - name: FactOnlineSales
      - name: FactSales

  - name: output_db
    database: "{{ env_var('DBT_OUTPUT_DB_NAME') }}"
    schema: cso