version: 2

sources:
  - name: input_db
    database: "{{ env_var('DBT_INPUT_DB_NAME') }}"
    schema: dbo
    tables:
      - name: VA_T_Datasets
      - name: VA_T_Fields
      - name: DS1
      - name: DS10
      - name: DS100
      - name: DS11
      - name: DS12
      - name: DS125
      - name: DS130
      - name: DS2
      - name: DS25
      - name: DS28
      - name: DS29
      - name: DS3
      - name: DS33
      - name: DS4
      - name: DS5
      - name: DS55
      - name: DS56
      - name: DS57
      - name: DS58
      - name: DS59
      - name: DS6
      - name: DS60
      - name: DS7
      - name: DS74
      - name: DS76
      - name: DS79
      - name: DS8
      - name: DS9
      - name: DS91
      - name: DS126
      - name: DS128
      - name: DS149
      - name: DS152
      - name: DS219
      - name: DS220
      - name: DS221
      - name: DS222
      - name: DS223
      - name: DS224
      - name: DS225
      - name: DS226
      - name: DS227
      - name: DS228
      - name: DS229
      - name: DS230
      - name: DS231
      - name: DS232
      - name: DS234
      - name: DS256
      - name: DS26
      - name: DS27
      - name: DS272
      - name: DS273
      - name: DS314
      - name: DS315
      - name: DS319
      - name: DS321
      - name: DS37
      - name: DS38
      - name: DS40
      - name: DS41
      - name: DS98
      - name: DS113
      - name: DS114
      - name: DS115
      - name: DS116
      - name: DS117
      - name: DS118
      - name: DS119
      - name: DS120
      - name: DS121
      - name: DS122
      - name: DS123
      - name: DS124
      - name: DS133
      - name: DS134
      - name: DS322
      - name: DS135
      - name: DS136
      - name: DS137
      - name: DS138
      - name: DS139
      - name: DS140
      - name: DS141
      - name: DS142
      - name: DS143
      - name: DS145
      - name: DS146
      - name: DS147
      - name: DS148
      - name: DS151
      - name: DS290
      - name: DS291
      - name: DS155
      - name: DS156
      - name: DS157
      - name: DS158
      - name: DS159
      - name: DS160
      - name: DS161
      - name: DS162
      - name: DS163
      - name: DS164
      - name: DS165
      - name: DS166
      - name: DS167
      - name: DS168
      - name: DS274
      - name: DS258
      - name: DS259
      - name: DS260
      - name: DS261
      - name: DS262
      - name: DS263
      - name: DS264
      - name: DS265
      - name: DS266
      - name: DS267
      - name: DS268
      - name: DS269
      - name: DS270
